/*!
PrivMX Web Endpoint.
Copyright © 2024 Simplito sp. z o.o.

This file is part of the PrivMX Platform (https://privmx.dev).
This software is Licensed under the PrivMX Free License.

See the License for the specific language governing permissions and
limitations under the License.
*/

import { BaseApi } from "./BaseApi.js";
import { CryptoApiNative } from "../native/CryptoApiNative.js";
import { BIP39 } from "../Types.js";

/**
 * Standalone cryptographic toolbox: secp256k1 key generation and derivation,
 * ECDSA signing, symmetric encryption, and BIP-39 mnemonic handling.
 *
 * All operations run locally in the C++/WASM core - nothing ever leaves the
 * browser, and no server is contacted. The API is connection-INDEPENDENT:
 * obtain it via {@link EndpointFactory.createCryptoApi} after
 * {@link EndpointFactory.setup}, with or without an open {@link Connection}.
 *
 * Its primary job is producing the user's identity key: a secp256k1 private
 * key in WIF format passed to {@link EndpointFactory.connect}. Container
 * encryption keys are ECIES-encrypted to the matching public key, so whoever
 * holds the private key can decrypt the user's data.
 *
 * All methods reject with `NativeError` when the WASM core reports a failure
 * (e.g. malformed key material) and throw `Error` when the underlying native
 * API has been freed.
 */
export class CryptoApi extends BaseApi {
    /**
     * Resolved from the {@link GlobalContainer} - use {@link EndpointFactory.createCryptoApi}.
     * @internal
     */
    constructor(
        private native: CryptoApiNative,
        ptr: number,
    ) {
        super(ptr);
    }

    /**
     * Signs arbitrary data with the user's private key.
     *
     * Computes an ECDSA signature over the SHA-256 hash of `data` using the
     * secp256k1 key decoded from WIF - entirely inside the WASM core, locally.
     *
     * Use it to prove authorship of application-level payloads; the
     * counterpart {@link verifySignature} checks the result against the
     * signer's public key.
     *
     * @param {Uint8Array} data arbitrary bytes to sign; they are hashed with
     *   SHA-256 before signing, so any length is fine
     * @param {string} privateKey signer's secp256k1 private key in WIF format,
     *   generated by {@link generatePrivateKey} or derived with
     *   {@link derivePrivateKey2}
     * @returns {Uint8Array} compact ECDSA signature - pass it together with the
     *   original data to {@link verifySignature}
     * @throws {NativeError} when `privateKey` is not a valid WIF-encoded key
     */
    async signData(data: Uint8Array, privateKey: string): Promise<Uint8Array> {
        return this.native.signData(this.servicePtr, [data, privateKey]);
    }

    /**
     * Checks whether a signature was produced over the given data by the owner
     * of the given public key.
     *
     * Verifies the compact ECDSA (secp256k1, SHA-256) signature locally in the
     * WASM core - no server involvement.
     *
     * Use it to authenticate payloads signed with {@link signData}; obtain the
     * signer's public key from `Connection.listContextUsers` or
     * {@link derivePublicKey}.
     *
     * @param {Uint8Array} data exact bytes that were originally passed to
     *   {@link signData} - any modification fails verification
     * @param {Uint8Array} signature compact ECDSA signature returned by
     *   {@link signData}
     * @param {string} publicKey signer's public ECC key in BASE58DER format,
     *   derived from their private key with {@link derivePublicKey} or found in
     *   `UserInfo.pubKey` from `Connection.listContextUsers`
     * @returns {boolean} `true` when the signature matches the data and key -
     *   only then should the application trust the payload
     */
    async verifySignature(data: Uint8Array, signature: Uint8Array, publicKey: string) {
        return this.native.verifySignature(this.servicePtr, [data, signature, publicKey]);
    }

    /**
     * Generates a new private ECC (secp256k1) key - the user's identity in
     * PrivMX.
     *
     * Runs locally in the WASM core: the seed (or secure random bytes) is
     * stretched with PBKDF2 (200 000 rounds, SHA-512) over a random salt into a
     * BIP-32 extended key, whose private part is returned in WIF format. The
     * random salt makes the result non-deterministic even for the same seed -
     * for repeatable derivation use {@link derivePrivateKey2}.
     *
     * Generate one key per user at registration, derive its public part with
     * {@link derivePublicKey} for the Context ACL, and pass the private key to
     * {@link EndpointFactory.connect}.
     *
     * @param {string} [randomSeed] optional entropy mixed into key generation;
     *   omit to use the CSPRNG alone
     * @returns {string} private key in WIF format - store it securely and use
     *   it with {@link EndpointFactory.connect} and {@link signData}
     */
    async generatePrivateKey(randomSeed?: string): Promise<string> {
        return this.native.generatePrivateKey(this.servicePtr, [randomSeed]);
    }

    /**
     * Deterministically derives a private ECC key from a password (legacy
     * variant).
     *
     * Stretches the password with PBKDF2 locally in the WASM core, using an
     * older derivation scheme kept only so keys created by previous SDK
     * versions remain reachable.
     *
     * Use it exclusively to recover keys originally derived with this method;
     * for anything new call {@link derivePrivateKey2}.
     *
     * @deprecated Use {@link derivePrivateKey2} for all new keys.
     * @param {string} password user-supplied secret the key is derived from;
     *   the same password and salt always yield the same key
     * @param {string} salt application-chosen string mixed into the hash;
     *   must match the salt used when the key was first derived
     * @returns {string} private key in WIF format, identical for identical
     *   inputs - usable with {@link EndpointFactory.connect}
     */
    async derivePrivateKey(password: string, salt: string): Promise<string> {
        return this.native.derivePrivateKey(this.servicePtr, [password, salt]);
    }

    /**
     * Deterministically derives a private ECC (secp256k1) key from a password -
     * the recommended path for password-based login.
     *
     * Runs PBKDF2 (200 000 rounds, SHA-512) over the password and salt locally
     * in the WASM core and converts the result to a WIF private key. The same
     * password and salt always produce the same key, and the password never
     * leaves the browser.
     *
     * Use it so users can log in with familiar credentials: derive the key on
     * every login and pass it to {@link EndpointFactory.connect} - no key
     * storage needed.
     *
     * @param {string} password user-supplied secret the key is derived from;
     *   a stronger password means a stronger key
     * @param {string} salt application-chosen string mixed into the hash (e.g.
     *   the user's login); must be identical on every derivation to yield the
     *   same key
     * @returns {string} private key in WIF format, identical for identical
     *   inputs - pass it to {@link EndpointFactory.connect}
     * @example
     * const cryptoApi = await EndpointFactory.createCryptoApi();
     * const privKey = await cryptoApi.derivePrivateKey2("user-password", "user@example.com");
     * const connection = await EndpointFactory.connect(privKey, solutionId, bridgeUrl);
     */
    async derivePrivateKey2(password: string, salt: string): Promise<string> {
        return this.native.derivePrivateKey2(this.servicePtr, [password, salt]);
    }

    /**
     * Computes the public key matching a private key.
     *
     * Multiplies the secp256k1 base point by the decoded WIF key locally in
     * the WASM core - a pure, deterministic EC operation.
     *
     * The public key is what other users (and the Bridge) see: register it in
     * the Context ACL, list it in `UserWithPubKey` arrays when creating
     * containers, and hand it to {@link verifySignature}.
     *
     * @param {string} privateKey private ECC key in WIF format, generated by
     *   {@link generatePrivateKey} or derived with {@link derivePrivateKey2}
     * @returns {string} matching public key in BASE58DER format - used in
     *   `UserWithPubKey` entries and {@link verifySignature}
     * @throws {NativeError} when `privateKey` is not a valid WIF-encoded key
     */
    async derivePublicKey(privateKey: string): Promise<string> {
        return this.native.derivePublicKey(this.servicePtr, [privateKey]);
    }

    /**
     * Generates a fresh random symmetric encryption key.
     *
     * Draws 32 random bytes (a 256-bit AES key) from the WASM core's CSPRNG -
     * locally, with no server involvement.
     *
     * Use it as the key for {@link encryptDataSymmetric} /
     * {@link decryptDataSymmetric} when the application needs to encrypt data
     * outside of PrivMX containers.
     *
     * @returns {Uint8Array} 32 random key bytes - pass them to
     *   {@link encryptDataSymmetric} and store them securely
     */
    async generateKeySymmetric(): Promise<Uint8Array> {
        return this.native.generateKeySymmetric(this.servicePtr, []);
    }

    /**
     * Encrypts a buffer with a symmetric key.
     *
     * Applies the core's authenticated AES-256 scheme locally in the WASM
     * module, embedding an integrity tag so tampering is detected on
     * decryption.
     *
     * Use it for application-level encryption of data you store outside
     * PrivMX containers; reverse with {@link decryptDataSymmetric} using the
     * same key.
     *
     * @param {Uint8Array} data plaintext bytes to encrypt; any length is
     *   accepted
     * @param {Uint8Array} symmetricKey 256-bit (32-byte) key generated by
     *   {@link generateKeySymmetric}
     * @returns {Uint8Array} ciphertext with embedded integrity data - feed it
     *   back to {@link decryptDataSymmetric}
     */
    async encryptDataSymmetric(data: Uint8Array, symmetricKey: Uint8Array): Promise<Uint8Array> {
        return this.native.encryptDataSymmetric(this.servicePtr, [data, symmetricKey]);
    }

    /**
     * Decrypts a buffer produced by {@link encryptDataSymmetric}.
     *
     * Runs the core's authenticated AES-256 decryption locally in the WASM
     * module and verifies the embedded integrity tag before returning any
     * plaintext.
     *
     * Use it with the same 32-byte key the data was encrypted with; a wrong
     * key or modified ciphertext is rejected rather than yielding garbage.
     *
     * @param {Uint8Array} data ciphertext returned by
     *   {@link encryptDataSymmetric}, including its integrity data
     * @param {Uint8Array} symmetricKey the same 256-bit key (from
     *   {@link generateKeySymmetric}) that encrypted the data
     * @returns {Uint8Array} original plaintext bytes, ready for application use
     * @throws {NativeError} when the key is wrong or the ciphertext has been
     *   modified (integrity check fails)
     */
    async decryptDataSymmetric(data: Uint8Array, symmetricKey: Uint8Array): Promise<Uint8Array> {
        return this.native.decryptDataSymmetric(this.servicePtr, [data, symmetricKey]);
    }

    /**
     * Converts a private key from PEM encoding to the WIF format used across
     * PrivMX.
     *
     * Re-encodes the key material locally in the WASM core - no cryptographic
     * transformation, only a format change.
     *
     * Use it to import keys generated by external tools (e.g. OpenSSL) so they
     * can be passed to {@link EndpointFactory.connect} or {@link signData}.
     *
     * @param {string} pemKey private key in PEM format, e.g. exported by
     *   OpenSSL or another external key tool
     * @returns {string} the same key in WIF format - accepted by
     *   {@link EndpointFactory.connect} and {@link signData}
     * @throws {NativeError} when the PEM input cannot be parsed as a private
     *   key
     */
    async convertPEMKeytoWIFKey(pemKey: string): Promise<string> {
        return this.native.convertPEMKeytoWIFKey(this.servicePtr, [pemKey]);
    }

    /**
     * Generates a fresh BIP-39 mnemonic together with the BIP-32 key it
     * encodes.
     *
     * Draws `strength` bits of entropy locally in the WASM core, encodes them
     * as a standard 12/24-word English mnemonic, and derives the matching
     * BIP-32 extended key (optionally hardened with a password).
     *
     * Use it to give users a human-writable backup phrase: show
     * `result.mnemonic` once, then use `result.extKey` (an {@link ExtKey}) -
     * e.g. `extKey.getPrivateKey()` - for {@link EndpointFactory.connect}.
     * Restore later with {@link fromMnemonic}.
     *
     * @param {number} strength entropy size in bits, a multiple of 32 - 128
     *   yields 12 words, 256 yields 24 words
     * @param {string} [password] optional extra secret mixed into key
     *   derivation; the same password is then required by {@link fromMnemonic}
     * @returns {BIP39} mnemonic, raw entropy, and the derived {@link ExtKey} -
     *   keep the mnemonic as backup, use the key to connect
     * @throws {NativeError} when `strength` is not a multiple of 32
     */
    async generateBip39(strength: number, password: string = ""): Promise<BIP39> {
        return this.native.generateBip39(this.servicePtr, [strength, password]);
    }

    /**
     * Restores a BIP-32 key from a previously issued BIP-39 mnemonic.
     *
     * Validates the word list and recomputes the extended key locally in the
     * WASM core - deterministic, so the same mnemonic and password always
     * reproduce the same key.
     *
     * Use it for account recovery: ask the user for the phrase generated by
     * {@link generateBip39}, then connect with the restored key's private part.
     *
     * @param {string} mnemonic 12/24-word BIP-39 phrase produced by
     *   {@link generateBip39} or {@link entropyToMnemonic}
     * @param {string} [password] the same optional password that was supplied
     *   when the mnemonic was generated - a different one yields a different key
     * @returns {BIP39} mnemonic, entropy, and the restored {@link ExtKey} -
     *   identical to the originally generated key
     * @throws {NativeError} when the mnemonic contains unknown words or fails
     *   its checksum
     */
    async fromMnemonic(mnemonic: string, password: string = ""): Promise<BIP39> {
        return this.native.fromMnemonic(this.servicePtr, [mnemonic, password]);
    }

    /**
     * Builds a BIP-39 mnemonic and BIP-32 key directly from raw entropy bytes.
     *
     * Encodes the entropy as a standard mnemonic and derives the extended key
     * locally in the WASM core - the byte-level equivalent of
     * {@link fromMnemonic}.
     *
     * Use it when the application stores raw entropy (e.g. from
     * {@link mnemonicToEntropy}) instead of the word list.
     *
     * @param {Uint8Array} entropy BIP-39 entropy bytes (16–32 bytes, a multiple
     *   of 4), e.g. returned by {@link mnemonicToEntropy} or from a CSPRNG
     * @param {string} [password] optional extra secret mixed into key
     *   derivation, as in {@link generateBip39}
     * @returns {BIP39} mnemonic, entropy, and the derived {@link ExtKey} for
     *   use with {@link EndpointFactory.connect}
     * @throws {NativeError} when the entropy length is not a valid BIP-39 size
     */
    async fromEntropy(entropy: Uint8Array, password: string = ""): Promise<BIP39> {
        return this.native.fromEntropy(this.servicePtr, [entropy, password]);
    }

    /**
     * Encodes raw BIP-39 entropy as its mnemonic word list.
     *
     * Pure local conversion in the WASM core (entropy + checksum → words) - no
     * key derivation happens.
     *
     * Use it to display a backup phrase for entropy the application already
     * holds; {@link mnemonicToEntropy} performs the inverse.
     *
     * @param {Uint8Array} entropy BIP-39 entropy bytes (16–32 bytes, a multiple
     *   of 4), e.g. from `BIP39.entropy` returned by {@link generateBip39}
     * @returns {string} 12/24-word mnemonic - accepted by {@link fromMnemonic}
     *   and {@link mnemonicToEntropy}
     * @throws {NativeError} when the entropy length is not a valid BIP-39 size
     */
    async entropyToMnemonic(entropy: Uint8Array): Promise<string> {
        return this.native.entropyToMnemonic(this.servicePtr, [entropy]);
    }

    /**
     * Decodes a BIP-39 mnemonic back into its raw entropy bytes.
     *
     * Pure local conversion in the WASM core (words → entropy, checksum
     * verified) - the inverse of {@link entropyToMnemonic}.
     *
     * Use it when the application prefers to persist compact entropy bytes
     * rather than the word list; restore the key later with
     * {@link fromEntropy}.
     *
     * @param {string} mnemonic 12/24-word BIP-39 phrase produced by
     *   {@link generateBip39} or {@link entropyToMnemonic}
     * @returns {Uint8Array} raw entropy bytes - accepted by
     *   {@link fromEntropy} and {@link entropyToMnemonic}
     * @throws {NativeError} when the mnemonic contains unknown words or fails
     *   its checksum
     */
    async mnemonicToEntropy(mnemonic: string): Promise<Uint8Array> {
        return this.native.mnemonicToEntropy(this.servicePtr, [mnemonic]);
    }

    /**
     * Stretches a BIP-39 mnemonic into the 64-byte seed defined by the BIP-39
     * standard.
     *
     * Runs PBKDF2 over the mnemonic and optional password locally in the WASM
     * core, exactly as BIP-39 specifies - deterministic for the same inputs.
     *
     * Use the seed for interoperability with other BIP-32 wallets/tools, or
     * feed it to {@link ExtKey.fromSeed} to build an extended key directly.
     *
     * @param {string} mnemonic 12/24-word BIP-39 phrase produced by
     *   {@link generateBip39} or {@link entropyToMnemonic}
     * @param {string} [password] optional passphrase mixed into the PBKDF2
     *   derivation, as in {@link generateBip39}
     * @returns {Uint8Array} 64-byte BIP-39 seed - usable with
     *   {@link ExtKey.fromSeed}
     */
    async mnemonicToSeed(mnemonic: string, password: string = ""): Promise<Uint8Array> {
        return this.native.mnemonicToSeed(this.servicePtr, [mnemonic, password]);
    }
}
