#!/bin/bash

set -e

SCRIPT_PATH=$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )

source "$SCRIPT_PATH/config.sh"
source "$EMSDK_DIR/emsdk_env.sh"

sep() {
    echo "=========================== $1 =========================="
}

sep "PRIVMX_WEBENDPOINT_DRV_CRYPTO_SRC"
cd "$PRIVMX_WEBENDPOINT_DRV_CRYPTO_SRC"
mkdir -p build-emscripten && cd build-emscripten
if [ ! -f CMakeCache.txt ]; then
    emcmake cmake .. -D CMAKE_BUILD_TYPE=MinSizeRel -D CMAKE_EXPORT_COMPILE_COMMANDS=ON
else
    echo "CMakeCache.txt exists — skipping cmake configure."
fi
emmake make -j20
emmake make install

sep "PRIVMX_WEBENDPOINT_DRV_ECC_SRC"
cd "$PRIVMX_WEBENDPOINT_DRV_ECC_SRC"
mkdir -p build-emscripten && cd build-emscripten
if [ ! -f CMakeCache.txt ]; then
    emcmake cmake .. -D CMAKE_BUILD_TYPE=MinSizeRel -D CMAKE_EXPORT_COMPILE_COMMANDS=ON
else
    echo "CMakeCache.txt exists — skipping cmake configure."
fi
emmake make -j20
emmake make install

sep "PRIVMX_WEBENDPOINT_DRV_NET_SRC"
cd "$PRIVMX_WEBENDPOINT_DRV_NET_SRC"
mkdir -p build-emscripten && cd build-emscripten
if [ ! -f CMakeCache.txt ]; then
    emcmake cmake .. -D CMAKE_BUILD_TYPE=MinSizeRel -D CMAKE_EXPORT_COMPILE_COMMANDS=ON
else
    echo "CMakeCache.txt exists — skipping cmake configure."
fi
emmake make -j20
emmake make install
