#!/bin/bash

set -e

SCRIPT_PATH=$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )

source "$SCRIPT_PATH/config.sh"
source "$EMSDK_DIR/emsdk_env.sh"

echo "Checking checksum: $PRIVMX_WEBENDPOINT_DRV_CONTEXT_SRC ..."
set +e
$SCRIPT_PATH/check_dir_checksum "$PRIVMX_WEBENDPOINT_DRV_CONTEXT_SRC"
RESULT=$?
set -e
case "$RESULT" in
    0)
        echo "No changes - skipping build"
        ;;
    1)
        echo "changes - rebuild..."
        cd "$PRIVMX_WEBENDPOINT_DRV_CONTEXT_SRC"

        npm ci --registry="https://npmregistry.privmx.com"
        npm run build

        set +e
        $SCRIPT_PATH/check_dir_checksum "$PRIVMX_WEBENDPOINT_DRV_CONTEXT_SRC"
        set -e
        ;;
    2)
        echo "\n\n\nBłąd wejścia" >&2
        exit 2
        ;;
    *)
        echo "\n\n\nNieznany kod wyjścia: $RESULT" >&2
        exit 3
        ;;
esac



