#!/bin/bash
SCRIPT_PATH=$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )
# cd $SCRIPT_PATH
# ./build_api vcurrent $1 && ./add_assets_to_npm && ./prepare_npm 1.0.0-devel "$SCRIPT_PATH"
source "$SCRIPT_PATH/../build-manifest.sh"
sep() {
    echo "=========================== $1 =========================="
}

sep "get_emsdk"
"$SCRIPT_PATH/get_emsdk"
sep "build_gmp"
"$SCRIPT_PATH/build_gmp" $GMP
sep "build_poco"
"$SCRIPT_PATH/build_poco" $POCO
sep "build_pson"
"$SCRIPT_PATH/build_pson" $PSON_CPP
sep "build_secp"
"$SCRIPT_PATH/build_secp"
sep "build_async_engine"
"$SCRIPT_PATH/build_async_engine"

sep "build_webdrivers"
"$SCRIPT_PATH/build_webdrivers"

sep "build_privmx_endpoint"
"$SCRIPT_PATH/build_privmx_endpoint" $PRIVMX_ENDPOINT
sep "build_driver_web_context"
"$SCRIPT_PATH/build_driver_web_context"
sep "build_api"
"$SCRIPT_PATH/build_api" $PRIVMX_ENDPOINT
"$SCRIPT_PATH/build_api" vcurrent
sep "add assets to npm"
"$SCRIPT_PATH/add_assets_to_npm"

"$SCRIPT_PATH/prepare_npm" 1.0.0-devel "$SCRIPT_PATH"
echo "BUILD SUCCESS"

