#!/bin/bash

set -e

SCRIPT_PATH=$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )

source "$SCRIPT_PATH/config.sh"
source "$EMSDK_DIR/emsdk_env.sh"

cd "$PRIVMX_WEBENDPOINT_DRV_CONTEXT_SRC"

npm ci --registry="https://npmregistry.privmx.com"
npm run build
