#!/bin/bash

set -e

SCRIPT_PATH=$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )

if [ -z "$1" ]; then
    echo "$0: Parameter missing."
    exit -1;
fi
VERSION=$1

source "$SCRIPT_PATH/config.sh"
source "$EMSDK_DIR/emsdk_env.sh"

GMP_DIR="$SOURCE_DIR/gmp-${VERSION}"

if [ -d "$GMP_DIR" ];
then
    echo "$GMP_DIR directory exists. Skip download of sources."
else
	echo "$GMP_DIR directory does not exist. Get sources..."
    cd "$SOURCE_DIR"
    # curl "https://ftp.gnu.org/gnu/gmp/gmp-$GMP_VERSION.tar.xz" --output gmp.tar.xz
    curl "https://gmplib.org/download/gmp/gmp-$VERSION.tar.xz" --output gmp.tar.xz
    tar -xf gmp.tar.xz
fi

cd "$GMP_DIR"

if [ ! -d "$GMP_DIR/build-emscripten" ]; then
    mkdir -p build-emscripten && cd build-emscripten
    emconfigure ../configure --disable-assembly --host none --enable-cxx --prefix=$SYSROOT_DIR CFLAGS="-Os" CXXFLAGS="-Os"
else
    cd build-emscripten
fi
emmake make -j$(nproc)
emmake make check || echo "TEST FAIL"
emmake make install
