#!/bin/bash

set -e

SCRIPT_PATH=$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )

source "$SCRIPT_PATH/config.sh"
source "$EMSDK_DIR/emsdk_env.sh"

cd "$PRIVMX_DRV_CRYPTO"

if [ ! -d "./build-emscripten" ]; then
    mkdir -p build-emscripten && cd build-emscripten
    emcmake cmake .. -D CMAKE_BUILD_TYPE=MinSizeRel
else
    cd build-emscripten
fi
emmake make -j20
emmake make install

cd "$PRIVMX_DRV_ECC"

if [ ! -d "./build-emscripten" ]; then
    mkdir -p build-emscripten && cd build-emscripten
    emcmake cmake .. -D CMAKE_BUILD_TYPE=MinSizeRel
else
    cd build-emscripten
fi
emmake make -j20
emmake make install

cd "$PRIVMX_DRV_NET"

if [ ! -d "./build-emscripten" ]; then
    mkdir -p build-emscripten && cd build-emscripten
    emcmake cmake .. -D CMAKE_BUILD_TYPE=MinSizeRel
else
    cd build-emscripten
fi
emmake make -j20
emmake make install
