#!/bin/bash
SCRIPT_PATH=$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )
set -euo pipefail

# ====== WALIDACJA PARAMETRÓW ======
if [[ $# -ne 1 ]]; then
    echo "Usage: $0 <directory>" >&2
    exit 2
fi
echo "Checking dir: $1"
DIR_TO_CHECK="$1/"

if [[ ! -d "$DIR_TO_CHECK" ]]; then
    echo "Error: '$DIR_TO_CHECK' is not a directory" >&2
    exit 2
fi
# ====== PLIKI STANU ======
DIR_HASH="$(echo -n "$DIR_TO_CHECK" | sha256sum | cut -d' ' -f1)"
STATE_FILE="/tmp/dir_checksum.${DIR_HASH}.prev"
TMP_FILE="$(mktemp)"

# ====== LICZENIE CHECKSUM ======
find "$DIR_TO_CHECK" -type f -print0 \
  | sort -z \
  | xargs -0 sha256sum > "$TMP_FILE"


# ====== PORÓWNANIE ======
if [[ ! -f "$STATE_FILE" ]]; then
    cp "$TMP_FILE" "$STATE_FILE"
    rm -f "$TMP_FILE"
    exit 1   # A – pierwszy raz

elif ! cmp -s "$TMP_FILE" "$STATE_FILE"; then
    cp "$TMP_FILE" "$STATE_FILE"
    rm -f "$TMP_FILE"
    exit 1   # A – zmiana

else
    rm -f "$TMP_FILE"
    exit 0   # B – brak zmian
fi
