#!/bin/bash
set -e

SCRIPT_PATH=$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )

source $SCRIPT_PATH/config.sh

if [ -d "$EMSDK_DIR" ]; then
    exit 0
fi

cd $BASE_DIR

mkdir -p "$SOURCE_DIR"

#sudo apt install -y git ant build-essential ca-certificates curl make cmake openssh-client python3 python3-pip wget zip inotify-tools

git clone https://github.com/emscripten-core/emsdk.git "$EMSDK_DIR"

cd $EMSDK_DIR

./emsdk install "$EMSDK_VERSION"
./emsdk activate "$EMSDK_VERSION"

patch -d "$EMSDK_DIR/upstream" -p1 -i "$BASE_DIR/patches/emsdk-upstream.patch"
