#!/bin/bash

set -e

SCRIPT_PATH=$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )
source "$SCRIPT_PATH/config.sh"
NPM_PACKAGE_VERSION="1.0.0"
if [ -n "$1" ]; then
    NPM_PACKAGE_VERSION="$1"
fi
WORKING_DIR="$PRIVMX_WEBENDPOINT_API_SRC/ts"
PUB_DIR="$WORKING_DIR/pub"

rm -rf "$PUB_DIR"
mkdir -p $PUB_DIR



cp $WORKING_DIR/package-template.json $WORKING_DIR/package.json
sed -i "s/{__VERSION__}/$1/g" $WORKING_DIR/package.json

cd $WORKING_DIR
npm run build
cp -R ./dist/* "$PUB_DIR"
cp -R ./assets "$PUB_DIR"
cp ./LICENSE.md "$PUB_DIR"
cp ./README.md "$PUB_DIR"
cp ./package.json "$PUB_DIR"

cd "$PUB_DIR"

OUT_FILE=`npm pack --pack-destination $OUT_DIR`


OUT_FILE_PATH="`cd $SCRIPT_PATH/.. && pwd`/out/$OUT_FILE"
echo "Generated NPM package can be found here: $OUT_FILE_PATH"
echo "You can call: npm install $OUT_FILE_PATH inside your project's directory to install it."