name: Tests

on:
  push:
    branches: [main, devel]
  pull_request:
    branches: [main, devel]
  workflow_dispatch:

concurrency:
  group: tests-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  ci:
    uses: ./.github/workflows/ci.yml
